server:
  port: 8094
  servlet:
    context-path: /api/v0

spring:
  profiles:
    active: local
  datasource:
    initialization-mode: always
    hikari:
      maximum-pool-size: 50
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
springdoc:
  api-docs:
    enabled: true

security:
  basic:
    enabled: false

management:
  health:
    defaults:
      enabled: false
  security:
    enabled: false
  endpoints:
    enabled-by-default: false
    health:
      enabled: false
    web:
      exposure:
        include: [ ]
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        allow-credentials: false
  endpoint:
    info:
      enabled: false

client:
  deep-ai:
    url: https://api.deepai.org/api/text2img
    api-key: quickstart-QUdJIGlzIGNvbWluZy4uLi4K
